In [36]:
import os
import tweepy
import json
import pandas as pd

outfilename = 'twitter_withrefugees.ldjson'
max_tweets = 100 # Number of tweets you want, remove from .items() call below if you want all
search_term = "#refugees" 
from_date = "2019-08-01" # Date you want to search from

In [37]:
# Set up twitter_config file containing a dictionary with your credentials
# I have several so this just pulls the first set of credentials
# The file should look like this but fill in your keys
# {'consumer_secret':'','consumer_key':'','access_token':'','access_token_secret':''}
config = []
with open('twitter_config','r') as inf:
    for line in inf:
        config.append(eval(line)) 

# You could also fill them in here instead but don't put it on github or share with anyone
consumer_key=config[0]['consumer_key']
consumer_secret=config[0]['consumer_secret']
access_token = config[0]['access_token']
access_token_secret = config[0]['access_token_secret']

In [38]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)
#####United Airlines
tweets = []
for tweet in tweepy.Cursor(api.search,
                           q=search_term,
                           count=1000,
                           lang="en",
                           since=from_date,
                           retweets=False).items(max_tweets):
    tweets.append(tweet._json)
    with open(outfilename, 'a') as f:
        json.dump(tweet._json, f)
        f.write('\n')

In [39]:
tweets[0].keys()

dict_keys(['created_at', 'id', 'id_str', 'text', 'truncated', 'entities', 'metadata', 'source', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'retweet_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'lang'])

In [40]:
print "Username: " + str(tweets[0]['user']['screen_name']) + '\n'
print "User Location: " + tweets[0]['user']['location'] + '\n'
print "Tweet text: " + tweets[0]['text'] + '\n'
print "Date of tweet: " + tweets[0]['created_at']

SyntaxError: invalid syntax (<ipython-input-40-696e8277dcc8>, line 1)

In [41]:
# To read file back in:
path_to_jsons = './'
json_files = [pos_json for pos_json in os.listdir(path_to_jsons) if pos_json.endswith('.ldjson')]
jsons = []
for js in json_files:
    with open(os.path.join(path_to_jsons, js)) as json_file:
        # do something with your json; I'll just print
        for line in json_file:
            jsons.append(json.loads(line))

In [42]:
# To flatten dictionaries into a pandas dataframe
def flattenDict(d, result=None):
    '''
    Creates pandas dataframe from nested dictionary
    '''
    if result is None:
        result = {}
    for key in d:
        value = d[key]
        if isinstance(value, dict):
            value1 = {}
            for keyIn in value:
                value1[".".join([key,keyIn])]=value[keyIn]
            flattenDict(value1, result)
        elif isinstance(value, (list, tuple)):   
            for indexB, element in enumerate(value):
                if isinstance(element, dict):
                    value1 = {}
                    for keyIn in element:
                        newkey = ".".join([key,keyIn])        
                        value1[".".join([key,keyIn])]=value[indexB][keyIn]
                    for keyA in value1:
                        flattenDict(value1, result)   
        else:
            result[key]=value
    return result

In [43]:
tweetdf = pd.DataFrame([flattenDict(tweet) for tweet in jsons])

In [44]:
tweetdf.columns

Index(['contributors', 'coordinates', 'created_at', 'entities.hashtags.text',
       'entities.media.display_url', 'entities.media.expanded_url',
       'entities.media.id', 'entities.media.id_str',
       'entities.media.media_url', 'entities.media.media_url_https',
       ...
       'user.profile_text_color', 'user.profile_use_background_image',
       'user.protected', 'user.screen_name', 'user.statuses_count',
       'user.time_zone', 'user.translator_type', 'user.url', 'user.utc_offset',
       'user.verified'],
      dtype='object', length=554)

In [45]:
tweetdf.head()

,contributors,coordinates,created_at,entities.hashtags.text,entities.media.display_url,entities.media.expanded_url,entities.media.id,entities.media.id_str,entities.media.media_url,entities.media.media_url_https,...,user.profile_text_color,user.profile_use_background_image,user.protected,user.screen_name,user.statuses_count,user.time_zone,user.translator_type,user.url,user.utc_offset,user.verified
0,None,None,Wed Sep 19 22:32:42 +0000 2018,WithRefugees,NaN,NaN,NaN,NaN,NaN,NaN,...,333333,True,False,RibanAbrahim,16698,None,none,None,None,False
1,None,None,Wed Sep 19 22:28:33 +0000 2018,WithRefugees,pic.twitter.com/4hKaoZjXwj,https://twitter.com/Refugees/status/1042521210...,1.041975e+18,1041975140354072576,http://pbs.twimg.com/amplify_video_thumb/10419...,https://pbs.twimg.com/amplify_video_thumb/1041...,...,000000,False,False,AulaniMulford,8676,None,none,None,None,False
2,None,None,Wed Sep 19 22:26:33 +0000 2018,EU,NaN,NaN,NaN,NaN,NaN,NaN,...,333333,True,False,mchf22,23266,None,none,None,None,False
3,None,None,Wed Sep 19 22:26:04 +0000 2018,EU,NaN,NaN,NaN,NaN,NaN,NaN,...,333333,True,False,AlbertJaimeC,48033,None,none,None,None,False
4,None,None,Wed Sep 19 22:22:34 +0000 2018,WithRefugees,pic.twitter.com/4hKaoZjXwj,https://twitter.com/Refugees/status/1042521210...,1.041975e+18,1041975140354072576,http://pbs.twimg.com/amplify_video_thumb/10419...,https://pbs.twimg.com/amplify_video_thumb/1041...,...,362720,True,False,daianapena,5249,None,none,None,None,False